steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/sudo-rm-rf:base || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/base.Dockerfile',
    '-t', 'sudo-rm-rf:base',
    '-t', 'gcr.io/$PROJECT_ID/sudo-rm-rf:base',
    '--cache-from', 'gcr.io/$PROJECT_ID/sudo-rm-rf:base',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sudo-rm-rf:base']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/Dockerfile',
    # define SECRET_KEY here
    '--build-arg', 'SECRET_KEY=secret-key',
    '-t', 'gcr.io/$PROJECT_ID/sudo-rm-rf:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-f', 'docker/coverage.Dockerfile',
    '-t', 'gcr.io/$PROJECT_ID/sudo-rm-rf:coverage',
    '.'
  ]
images: ['gcr.io/$PROJECT_ID/sudo-rm-rf:base', 'gcr.io/$PROJECT_ID/sudo-rm-rf:latest']
